# Generated by Django 3.0 on 2024-04-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_move_data_to_profiles'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS oc_lettings_site_profile;"),
    ]
