version: 2

# Build environment configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
# Build configuration for Sphinx
sphinx:
  configuration: docs/conf.py

# Python configuration
python:
  install:
    - requirements: docs/requirements.txt

# Output formats
formats:
  - pdf
  - epub
