# .readthedocs.yaml

version: 2

# Build documentation in the "docs" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally specify the Python version you want to use
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

# Build using a "stable" version
formats:
  - html
  - pdf
  - epub

# Environment variables for the build process
build:
  image: latest

# You can add other configurations here as needed
