# .readthedocs.yaml

version: 2

# Build configuration for Sphinx
sphinx:
  configuration: docs/conf.py

# Python configuration
python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt

# Output formats
formats:
  - htmlzip
  - pdf
  - epub

# Build environment configuration
build:
  os: ubuntu-22.04
