# Utilisez une image de base avec Python 3.11
FROM python:3.11-slim

# Installez les dépendances
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copiez l'application
COPY . .

# Définez le répertoire de travail
WORKDIR /app

# Commande par défaut pour lancer l'application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
