# Utilisez une image de base avec Python 3.10
FROM python:3.10-slim

# Installez les dépendances de base
COPY requirements.txt .
RUN apt-get update && apt-get install -y wget gnupg && \
    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' && \
    apt-get update && apt-get install -y google-chrome-stable && \
    pip install --upgrade pip && \
    pip install --no-cache-dir --no-build-isolation -r requirements.txt && \
    rm -rf /root/.cache/pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Installez les dépendances de test
COPY requirements-tests.txt .
RUN pip install --no-cache-dir --no-build-isolation -r requirements-tests.txt && \
    rm -rf /root/.cache/pip

# Copiez l'application
COPY . .

# Définez le répertoire de travail
WORKDIR /app

# Commande par défaut pour exécuter les tests
CMD ["python", "manage.py", "test"]
