version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Base Docker image avec Python et Docker CLI
    steps:
      - checkout  # Vérification du code source depuis le dépôt Git
      - setup_remote_docker:
          version: 20.10.7  # Configuration de l'environnement Docker isolé
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: python manage.py test
      - run:
          name: Build Docker Image
          command: docker build -t lejinge/oc-lettings:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push lejinge/oc-lettings:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master  # Se déclenche uniquement sur la branche master
