version: 2.1

executors:
  docker-executor:
    docker:
      - image: lejinge/oc-lettings:test
    working_directory: ~/repo
    resource_class: large  # Augmente les ressources

jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run tests in Docker
          command: python manage.py test
      - run:
          name: Generate coverage report
          command: |
            coverage run --source='.' manage.py test
            coverage report --fail-under=80
            coverage xml
      - store_artifacts:
          path: coverage.xml
          destination: coverage.xml

  build_prod_image:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image for production
          command: docker build -f Dockerfile.prod -t oc-lettings:latest .

  push_prod_image:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Tag Docker image
          command: docker tag oc-lettings:latest ${DOCKERHUB_USERNAME}/oc-lettings:latest
      - run:
          name: Push Docker image
          command: docker push ${DOCKERHUB_USERNAME}/oc-lettings:latest

workflows:
  version: 2
  build_test_push:
    jobs:
      - test
      - build_prod_image:
          requires:
            - test
      - push_prod_image:
          requires:
            - build_prod_image
          filters:
            branches:
              only: master
