version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests with coverage
          command: |
            coverage run --source='.' manage.py test
            coverage report --fail-under=80
            coverage xml
      - store_artifacts:
          path: coverage.xml
          destination: coverage.xml

  build_and_push:
    docker:
      - image: circleci/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t lejinge/oc-lettings:latest .
      - run:
          name: Push Docker image
          command: docker push lejinge/oc-lettings:latest

workflows:
  version: 2
  test_build_push:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
