version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    resource_class: large  # Augmente les ressources

jobs:
  build_test_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image for testing
          command: docker build -f Dockerfile.test -t oc-lettings:test .

  start_server:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Start Django server
          command: docker run -d --name test_server -p 8000:8000 lejinge/oc-lettings:test gunicorn --bind 0.0.0.0:8000 myapp.wsgi:application

  test:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Run tests in Docker
          command: docker run --rm oc-lettings:test python manage.py test
      - run:
          name: Generate coverage report
          command: |
            docker run --rm oc-lettings:test coverage run --source='.' manage.py test
            docker run --rm oc-lettings:test coverage report --fail-under=80
            docker run --rm oc-lettings:test coverage xml
      - store_artifacts:
          path: coverage.xml
          destination: coverage.xml

  build_prod_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image for production
          command: docker build -f Dockerfile.prod -t oc-lettings:latest .

  push_prod_image:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Tag Docker image
          command: docker tag oc-lettings:latest ${DOCKERHUB_USERNAME}/oc-lettings:latest
      - run:
          name: Push Docker image
          command: docker push ${DOCKERHUB_USERNAME}/oc-lettings:latest

workflows:
  version: 2
  build_test_push:
    jobs:
      - build_test_image
      - start_server:
          requires:
            - build_test_image
      - test:
          requires:
            - build_test_image
      - build_prod_image:
          requires:
            - test
      - push_prod_image:
          requires:
            - build_prod_image
          filters:
            branches:
              only: master
